server:
  port: 8086

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            tutorial-front:
              - uri: http://127.0.0.1:8081
                metadata:
                  management.context-path: /actuator
            tutorial-backend:
              - uri: http://127.0.0.1:9090
                metadata:
                  management.context-path: /actuator
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      notify:
        mail:
          from: Spring Boot Admin <noreply@test.com>
          to: imad@gmail.com
          cc: laghrissi@gmail.com
  mail:
    username: adresse.noreply@test.com
    password:
    host: 127.0.0.1
    port: 2525
    protocol: smtp
    ui:
      cache:
        no-cache: true
      template-location: file:../../spring-boot-admin-server-ui/target/dist/
      resource-locations: file:../../spring-boot-admin-server-ui/target/dist/
      cache-templates: false
      extension-resource-locations: file:../spring-boot-admin-sample-custom-ui/target/dist/
    client:
      username: admin
      password: admin